services:
  #Database
  wasatch_db:
    image: mariadb:11.3.2
    volumes:
      - ./db_data:/var/lib/mysql
    ports:
      - 3332:3306
    restart: always
    env_file: .env
    environment:
      MARIADB_ROOT_PASSWORD: $MARIADB_ROOT_PASSWORD
      MARIADB_DATABASE: wordpress
    container_name: wasatch_db
  #Web
  wasatch_wp:
    depends_on:
      - wasatch_db
    build:
      dockerfile: ./Dockerfile
      context: .
    ports:
      - 8094:80
    restart: always
    env_file: .env
    environment:
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_HOST: wasatch_db
      WORDPRESS_DB_USER: $MYSQL_USER
      WORDPRESS_DB_PASSWORD: $MYSQL_PASSWORD
      WORDPRESS_TABLE_PREFIX: wp_
    container_name: wasatch_wp
    volumes:
      - ./wp-content:/var/www/html/wp-content
  #PhpMyAdmin
  wasatch_myadmin:
    image: phpmyadmin:latest
    container_name: wasatch_myadmin
    restart: "no"
    ports:
      - 5014:80
    environment:
      PMA_HOST: wasatch_db
      UPLOAD_LIMIT: 100M
    depends_on:
      - wasatch_db
volumes:
  db_data:
  wp-content:
